name: cicd-workflow 
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  ci: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install 
      - name: Run test
        run: npm test
    env: 
      SERVER_SECRET: ${{ secrets.SERVER_SECRET }} 
      SERVER_URI: ${{ secrets.SERVER_URI }} 
      SERVER_EMAIL: ${{ secrets.SERVER_EMAIL }} 
      PLATFORM_URI: ${{ secrets.PLATFORM_URI }} 
      MONGODB_URI: ${{ secrets.MONGODB_URI }} 

  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - name: SSH connection to the remote system
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/se2/6/se2-backend
            git reset --hard origin/main 
            git fetch
            git pull https://${{ secrets.CLONE_TOKEN }}@github.com/SoftwareEngineering2-Assignment/se2-backend-group-6 main
            # git clone https://github.com/SoftwareEngineering2-Assignment/se2-backend-group-6 .
            bash -ci 'npm install'
            bash -ci 'pm2 restart se2-backend-6'
